databases:
  - name: suppliers_db
    plan: free
    databaseName: suppliers
    user: etadmin

services:
  - type: web
    plan: free
    name: suppliers
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn suppliers.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: suppliers_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SUPERUSER_USERNAME
        value: "etadmin"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "etadmin"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "super@usersuperrrrr.fi"